apiVersion: v1
kind: Service
metadata:
  name: react-service
spec:
  selector:
    app: react
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      nodePort: 30080  # accessible depuis ton navigateur
      # De 30000 à 32767 - C’est la zone de ports réservée à NodePort.
  type: NodePort

# est ce que react a besoin de communiquer avec node? si c'est le cas on doit definir le service 
#pour qu'il puisse communiquer avec nodejs? commment faire 
